sample_pattern: .*

report_dir: public/09-dobrava-mapping

trim:
    read_type: original
    crop: 500
    quality: 20
    headcrop: 0
    minlen: 35

mapping:
    read_type: trimmed
    reference: dobrava
    params: --very-sensitive
