sample_pattern: '[^/]+'

blast:
    fasta_dir: representatives
    protein: True
    enabled: True
    max_target_seqs: 25
    report:
        max_query_seqs: 20000
        max_subject_seqs: 25
        min_query_coverage: 0.5
