sample_pattern: '[^/]+'

blast:
    enabled: True                 # Do you want to generate blast reports?
    fasta_dir: representatives    # Directory with .fa files, relative path from the root project directory

    query_type: nucleotide        # Nucleotide or protein, according to sequence type in input .fa files
    target_type: protein          # Nucleotide or protein, according to sequence type in blast database
    reference: virprot            # Blast database to be used (located at reference/<reference>/blast_index/<reference>.psq)
    max_target_seqs: 25           # Number of best hit reference sequences from blast database for each input sequence

    report:
        max_query_seqs: 20000     # Number of input sequences that would be reported
        max_subject_seqs: 25      # Number of reported best hit reference sequences from blast database
        min_query_coverage: 0.5   # Filter hits with lesser aligned part of the input sequence to the reference

    include:                      # Optional columns in the summary HTML report
        - coverage                # Number of aligned reads per contig
        - virfinder               # Probability that contig is from virus