sample_pattern: .*
report_dir: report/01-assembly
threads: 10

reads:
    preprocess:
        trimmed:
            method: trimmomatic
            temporary: False
            crop: 500
            quality: 20
            headcrop: 20
            minlen: 35

        decontaminated:
            method: bowtie2
            temporary: False
            references:
                - mhv
            keep: True

        deduplicated:
            method: fastuniq
            temporary: False

    report:
        quality_report:
            method: fastqc
            read_types:
                - trimmed
                - deduplicated
                - subsampled

assembly:
    assembler:
        method: spades
        mode: standard
        careful: True

    report:
        quality_report:
            method: quast

        assembly_graph:
            method: bandage