sample_pattern: .*

trim:
    read_type: original
    crop: 500
    quality: 20
    headcrop: 0
    minlen: 35

assembly:
    read_type: trimmed    # original, trimmed, deduplicated
    analysis_type: meta   # standard, meta, plasmid
    path_to_reference: reference/mhv68/mhv68.fa
