sample_pattern: .*

gene_pattern:
    silva-16S: .*16S.*
    silva-28S: .*28S.*

trim:                                   # Pre-process of reads, eliminate low quality sequences
    read_type: original                 # Location of fastq files, would be searched in reads/<read_type>/*_R1.fastq.gz
    crop: 500                           # Cut the read to a specified length
    quality: 20                         # Cut read, once the average quality within the 5bp window falls below a threshold
    headcrop: 20                         # Cut the specified number of bases from the start of the read
    minlen: 35                          # Drop the read if it is below a specified length
    temporary: True                     # Trimmed fastq files are deleted after all rules that use it as an input are completed

deduplicate:
    read_type: trimmed
    temporary: True

emirge:
    read_type: deduplicated

report:
    tsv:
        remove_marginal_taxes: True
