sample_pattern: .*

gene_pattern:
    silva-ssu-128: .*16S.*
    silva-lsu-128: .*28S.*

trim:
    read_type: original
    crop: 170
    quality: 20
    headcrop: 20
    minlen: 35

deduplicate:
    read_type: trimmed

emirge:
    read_type: deduplicated

report:
    tsv:
        remove_marginal_taxes: True
