sample_pattern: .*

trim:
    read_type: original
    crop: 170
    quality: 20
    headcrop: 20
    minlen: 35

emirge:
    read_type: trimmed
    reference: silva-ssu-128

report:
    tsv:
        remove_marginal_taxes: True
