sample_pattern: .*

subsample:
    read_type: deduplicated
    read_count: 100000

metaxa2:
    read_type: subsampled
    gene: ssu # ssu or lsu

report:
    tsv:
        remove_marginal_taxes: False

lefse:
    comparisons:
        - country

