sample_pattern: .*

gene_pattern:
    ssu: .*16S.*
    its_unite: .*ITS.*

trim:
    read_type: original
    crop: 500
    quality: 10
    headcrop: 10
    minlen: 35

prefilter:
    read_type: trimmed
    references:
        - hg38
        - pacnes

join:
    read_type: filtered

rdp:
    read_type: joined
    confidence: 0.5

report:
    tsv:
        remove_marginal_taxes: False
