sequencing: paired_end
samples:                            # List of sample categories to be analysed
    - name: .*-16S                  # Another category of samples, with names that end with "-ITS"
      reference: silva-16S-90-filtered          # Reference genome for reads in the category (reference/silva-16S/silva-16S.fa)
      description:
        overwrite: True             #True or False
        format: '{year}-{wine}-{wineyard}-16S' # napr. 2021-R-S_R1.fastq.gz
        attributes: # https://pypi.org/project/parse/
            year:
                type: int
            wine:
                type: categorical
                values:
                    R: rulandske
                    M: merlot
            wineyard:
                type: categorical
                values:
                    M: modra
                    S: svaty_jur

report_dir: report      # Generated reports and essential output files would be stored there
threads: 16                         # Number of threads to use in analysis

qiime2:
    import:
        manifest:
            method: create_manifest
        data:
            method: import
            sequence_type: manifest # allowed: EMP, MultiplexedBarcodeInSequence, MultiplexedBarcodeInSequence, manifest
        