sequencing: paired_end

samples:                            # List of sample categories to be analysed
    - name: .*                      # Another category of samples, with names that end with "-ITS"
      reference: silva-16S-90-filtered  # Reference genome for reads in the category (reference/silva-16S/silva-16S.fa)
      description:
        overwrite: True             #True or False
        format: '{year}-{wine}-{additive}-{material}-{rRNA}-{phase}-{biological_replica}{technical_replica:d}' # napr. 2021-R-S_R1.fastq.gz
        attributes: # https://pypi.org/project/parse/
            year:
                type: numeric
                values:
                    17: 2017
                    18: 2018
                    19: 2019
                    20: 2020
            wine:
                type: categorical
                values:
                    rb: rulandske biele
            additive:
                type: categorical
                values:
                    noth: nothing added
                    ctrl: control - commercial Saccharomyces cerevisiae only
                    sace: Saccharomyces serevisiae
                    mesa: Metschnikowia pulcherrima and Saccharomyces cerevisiae
                    lasa: Lachancea thermotolerans and Saccharomyces cerevisiae
                    must: initial must
            material:
                type: categorical
                values:
                    dna: DNA
                    rna: RNA
            rRNA:
                type: categorical
                values:
                    16S: 16S
                    28S: 28S
            phase:
                type: categorical
                values:
                    m0: initial must
                    m1: must
                    m2: fermented must
                    m3: young wine
                    m4: wine before filtration
                    m5: wine after filtration
            biological_replica:
                type: categorical
                values:
                    repA: first replica
                    repB: second replica
                    repC: third replica
            technical_replica:
                type: numeric
                values:
                    1: 1
                    2: 2
                    3: 3


report_dir: report                  # Generated reports and essential output files would be stored there
threads: 16                         # Number of threads to use in analysis

qiime2:
    import:
        manifest:
            method: create_manifest
        data:
            method: import
            PHRED_offset: 33        # allowed: 33,64 (33 used in Sanger, Illumina1.8, 64 used in Illumina 1.3), default: 33
    
    preprocess:
        demultiplex:
            method: cutadapt        # see https://docs.qiime2.org/2021.8/plugins/available/cutadapt/trim-paired/
            minlen: 35              # Minimal length of trimmed read. Shorter reads would be removed. (Must be higher or equal to 1, default: 1)
            max_error_rate: 0.1     # Maximum allowed error rate (Must be from range 0-1, default: 0.1)
                
        #paired have more parameters, how to handle it? e.g. trunc_len_f a trunc_len_r namiesto trunc_len
        denoise:  #https://docs.qiime2.org/2021.8/plugins/available/dada2/denoise-paired/
            method: dada2           # allowed dada2, deblur (requires quality_filter and joining if paired-end)
            trunc_len_f: 150        # position where truncation starts on forward, discard reads if shorter, if zero, dont do truncation
            trunc_len_r: 150        # position where truncation starts on reverse, discard reads if shorter, if zero, dont do truncation
            trim_left_f: 0          # how many bases trims from start on forward strand, set to 0 for no trimming (default: 0)
            trim_left_r: 0          # how many bases trims from start on reverse strand, set to 0 for no trimming (default: 0)
            max_ee_f: 2.0           # forward reads with expected errors higher than this value are discarded (default: 2.0)
            max_ee_r: 2.0           # reverse reads with expected errors higher than this value are discarded (default: 2.0)
            trunc_start_qual: 2     # truncate read from the first occurence of quality lower than this value, (default: 2)
            min_overlap: 4          # min length of overlap required for merging forward and reverse reads (default: 12)
            denoise_pooling: independent    # allowed 'independent', 'pseudo'; denoise samples independently, or use pseudo-pooling (default: independent)
            chimera_method: consensus       # allowed 'consensus', 'pooled', 'none' (default: consensus)
            chimera_parent_abundance: 1.0   # when tested for chimeric, this gives the minimum abundance of parents, (default: 1.0)
            num_reads_train: 1000000        # number of reads used for training error model, lower number = faster, but less reliable model (default: 1000000)
        
    report:
        #core_features:
            #https://docs.qiime2.org/2021.8/plugins/available/feature-table/core-features/
        #heatmap:
            #https://docs.qiime2.org/2021.8/plugins/available/feature-table/heatmap/
        export:
            method: export
            #representative_seqs: True #
            #feature_table: True
            #denoising_stats: True
            #core_features: True
            #heatmap: True

        # 3 pipelines:
            # dada2 -> ASVs
            # (join-pairs), quality filter, deblur -> ASVs 
            # (join-pairs), quality filter, dereplicate, OTU clustering, chimera, abundance filtering -> OTUs

        #quality_filter:         # required when using DEBLUR
        #    method: qscore      # see https://docs.qiime2.org/2021.8/plugins/available/quality-filter/q-score/
        #    min_quality: 4      # scores less than this value are considered low 
        #    window_size: 3      # low score succession longer than this value are truncated from read
        #    min_length_fraction: 0.75 #if truncating results in read length of lesser fraction than this value, then read is not kept
        #    max_ambiguous: 0    # how many ambiguous bases can occur in truncated read

        #joining...

        #dereplicate:
        #    method: vsearch_dereplicate_sequences # allowed 'vsearch_dereplicate_sequences'
        
        #clustering...

    analysis:
        phylogeny:
            method: fasttree # allowed: fasttree, iqtree, raxml
            max-gap-freq: 1.0 # float 0-1, maximum frequency of gap characters in a column for the column to be retained (if 1 - retains all, default: 1.0)
            min-conservation: 0.4 # float 0-1, minimum relative frequency of at least one non-gap character in a column for that column to be retained (if 0.4, column must contain a gapless character occuring at least 40% of sequences, default: 0.4)

