sample_pattern: .*
report_dir: public/01-metaxa2

gene_pattern:
    ssu: .*16S.*
    lsu: .*28S.*

trim:
    read_type: original
    crop: 170
    quality: 20
    headcrop: 20
    minlen: 35

metaxa2:
    read_type: trimmed
    confidence: 0.8

report:
    tsv:
        remove_marginal_taxes: False