sample_pattern: .*

gene_pattern:
    ssu: .*16S.*
    lsu: .*28S.*

trim:
    read_type: original
    crop: 170
    quality: 20
    headcrop: 20
    minlen: 35

metaxa2:
    read_type: trimmed

report:
    tsv:
        remove_marginal_taxes: False