sample_pattern: .*

trim:
    read_type: original
    crop: 170
    quality: 20
    headcrop: 20
    minlen: 35

metaxa2:
    read_type: trimmed
    gene: ssu # ssu or lsu

report:
    tsv:
        remove_marginal_taxes: False