sample_pattern: .*

trim:
    read_type: original
    crop: 500
    quality: 20
    headcrop: 0
    minlen: 35

mapping:
    read_type: trimmed
    reference: mhv68
    params: --very-sensitive

variant:
    min_nonref_allele_freq: 0.5
    min_coverage: 20
    keep_indels: False