sample_pattern: .*

trim:
    read_type: original
    crop: 500
    quality: 20
    headcrop: 0
    minlen: 35

mapping:
    read_type: deduplicated
    reference: bl21
    params: --very-sensitive
    read_group:
        map_type: ''
    dedup:
        map_type: read_group
    realign:
        map_type: dedup

variant:
    map_type: realign
    min_nonref_allele_freq: 0.2
    min_alternate_count: 2
    min_coverage: 10
    keep_indels: True