samples:
    - name: example.*
      reference: mhv

report_dir: report/01-fastqc_report
threads: 10

reads:
    report:
        quality_report:
            method: fastqc
            read_types:
                - original
