sample_pattern: dobv_003
report_dir: public/01-fast_virome_explorer

trim:                                   # Pre-process of reads, eliminate low quality sequences
    read_type: original                 # Location of fastq files, would be searched in reads/<read_type>/*_R1.fastq.gz
    crop: 500                           # Cut the read to a specified length
    quality: 20                         # Cut read, once the average quality within the 5bp window falls below a threshold
    headcrop: 20                         # Cut the specified number of bases from the start of the read
    minlen: 35                          # Drop the read if it is below a specified length
    temporary: True                     # Trimmed fastq files are deleted after all rules that use it as an input are completed

fast_virome_explorer:
    reference: refseq
    read_type: trimmed
    kmer_size: 31
