sample_pattern: .*
report_dir: report/01-assembly
threads: 10

reads:
    preprocess:
        trimmed:
            method: trimmomatic
            temporary: False
            crop: 500
            quality: 20
            headcrop: 20
            minlen: 35

        decontaminated:
            method: bowtie2
            temporary: False
            references:
                - mhv
            keep: True

        deduplicated:
            method: fastuniq
            temporary: False

    report:
        quality_report:
            method: fastqc
            read_types:
                - trimmed
                - deduplicated
                - subsampled

assembly:
    assembler:
        method: spades
        mode: standard
        careful: True

    report:
        quality_report:
            method: quast

        assembly_graph:
            method: bandage

classification:
    contig_based:
        method: blast
        reference:
            mhv:
                query_type: nucleotide        # Nucleotide or protein, according to sequence type in input .fa files
                target_type: nucleotide       # Nucleotide or protein, according to sequence type in blast database
                max_target_seqs: 10           # Number of best hit reference sequences from blast database for each input sequence
#            nt:
#                query_type: nucleotide        # Nucleotide or protein, according to sequence type in input .fa files
#                target_type: nucleotide       # Nucleotide or protein, according to sequence type in blast database
#                max_target_seqs: 10           # Number of best hit reference sequences from blast database for each input sequence
#
#            refviral:
#                query_type: nucleotide        # Nucleotide or protein, according to sequence type in input .fa files
#                target_type: protein          # Nucleotide or protein, according to sequence type in blast database
#                max_target_seqs: 10           # Number of best hit reference sequences from blast database for each input sequence
#
#            univiral:
#                query_type: nucleotide        # Nucleotide or protein, according to sequence type in input .fa files
#                target_type: protein          # Nucleotide or protein, according to sequence type in blast database
#                max_target_seqs: 10           # Number of best hit reference sequences from blast database for each input sequence

    viral:
        identification:
            method: virfinder

    report:
        summary:
            method: fasta_summary
            max_query_seqs: 20000     # Number of input sequences that would be reported
            max_target_seqs: 5        # Number of reported best hit reference sequences from blast database
            min_query_coverage: 0.01  # Filter hits with lesser aligned part of the input sequence to the reference
            include:                      # Optional columns in the summary HTML report
                - virfinder               # Probability that contig is from virus
#                - coverage                # Number of aligned reads per contig
                - blast                   # Homologues identified by Blast against specified reference databases

            html:                     # Attributes applicable only for the HTML report, would NOT be used in the TSV table
                seqs_per_page: 100        # Number of table rows (sequences) per page
                sort_by: 'Sequence'       # Rows would be sorted according to values in this column
                sort_how: 'asc'           # Values would be sorted in desc(ending) or asc(ending) order
                columns:                  # Show only attributes that start with the name, in this order
                    - Sequence
                    - Length
                    - Compress ratio
                    - Coverage
                    - VirFinder pvalue
                    - Homologue link
                    - Mapped reads
