# Load configuration file
configfile: srcdir('config.yaml')

# Run startup scripts that automatically loads imports from src/ and load helper methods
include: config['snake_dir'] + '/common/preambule.snake'

# Import sub-workflows
include: srcdir('Snakefile.assembly')
include: srcdir('Snakefile.read_quality_report')
include: srcdir('Snakefile.preprocess')

rule finalise__identify_viruses:
    """
    Pipeline annotates assembled contigs from preprocessed reads. Annotations, such as homologies with
    reference databases, coverage and results of prediction tools are presented in sortable, filterable HTML table.
    """
    input:
        rules.finalise__quality_report.output,
        rules.finalise__preprocess_reads.output,
        rules.finalise__assemble_reads.output,

        # Summary HTML report with annotations of assembled contigs
        summary_html = expand('assembly/{sample}/annotation/contigs/summary.html',
                               sample=pipeline.samples),

    output:
        # Summary HTML report with annotations of assembled contigs
        summary_html = expand('{report_dir}/{sample}/contig_annotations.html',
                               sample=pipeline.samples, report_dir=config['report_dir']),

    run:
        copy_input_files_with_consistent_output_names(input, output)

# Target rule would be executed locally, not on cluster
localrules: finalise__identify_viruses