sample_pattern: .*

trim:
    read_type: original
    crop: 500
    quality: 20
    headcrop: 0
    minlen: 35

assembly:
    read_type: trimmed

blast:
    enabled: True
    max_target_seqs: 10

kallisto:
    read_type: trimmed
    bootstrap_samples: 100