# Import sub-workflow
include: config['snakelines_dir'] + '/pipeline/standard_analysis/preprocess/Snakefile.rule'
include: config['snakelines_dir'] + '/pipeline/standard_analysis/read_quality_report/Snakefile.rule'

# Load configuration file
configfile: srcdir('config.yaml')

# Run startup scripts that automatically loads imports from src/ and load helper methods
include: config['snakelines_dir'] + '/src/snakelines.snake'

# Find in configuration read preprocess types that should be generated
preprocess = extract_from_config(config, ['reads', 'preprocess'], {})
read_types_to_keep = [read_type for read_type in preprocess.keys() if not preprocess[read_type].get('temporary', True)]
