sample_pattern: .*

trim:                                   # Pre-process of reads, eliminate low quality sequences
    read_type: original                 # Location of fastq files, would be searched in reads/<read_type>/*_R1.fastq.gz
    crop: 500                           # Cut the read to a specified length
    quality: 20                         # Cut read, once the average quality within the 5bp window falls below a threshold
    headcrop: 0                         # Cut the specified number of bases from the start of the read
    minlen: 35                          # Drop the read if it is below a specified length

mapping:
    read_type: trimmed                  # Location of reads to map, would be searched in reads/<read_type>/*_R1.fastq.gz
    reference: hg38                     # Reference genome, should be located at reference/<reference>/<reference>.fa
    params: --very-sensitive            # Additional parameters of the mapper
    read_group:                         # Add information of sequencing run to the bam header
        map_type: ''                    # Input BAM for the operation, <mapper>/<reference>/<map_type>/*.bam
    dedup:                              # Mark reads that are most likely PCR duplicates
        map_type: read_group            # Input BAM for the operation, <mapper>/<reference>/<map_type>/*.bam
    realign:                            # Realign reads in regions with indels
        map_type: dedup                 # Input BAM for the operation, <mapper>/<reference>/<map_type>/*.bam

variant:                                # Find genomic variation present in aligned reads (BAM)
    panel: truseq                       # Regions where to search for variation, reference/<reference>/annotation/<panel>/regions.bed
    map_type: realign                   # Input BAM for the operation, <mapper>/<reference>/<map_type>/*.bam
    hard_filter:                        # Variants that do not pass any of these filters would NOT be present in the VCF file
        min_nonref_allele_freq: 0.05    # Minimal proportion of reads with alternative allele against all observations
        min_alternate_count: 2          # Minimal number of reads with alternative allele
        min_map_quality: 15             # Minimal average mapping quality of reads with alternative allele
    soft_filter:                        # Failing these filters would be indicated in the FILTER field of the VCF file
        min_map_quality: 20             # Minimal average mapping quality of reads with alternative allele
        read_depth: 10                  # Minimal number of reads with alternative allele
        min_nonref_allele_freq: 0.20    # Minimal proportion of reads with alternative allele against all observations
        min_mean_base_quality: 20       # Minimal average base quality of bases that support alternative allele