sample_pattern: .*

trim:
    read_type: original
    crop: 140
    quality: 20
    headcrop: 15
    minlen: 35

deduplicate:
    read_type: trimmed

trinity:
    read_type: deduplicated
    design: rna-totl
    min_contig_len: 200

blast:
    protein: False
    enabled: True
    max_target_seqs: 25
    report:
        max_query_seqs: 20000

kallisto:
    read_type: deduplicated
    bootstrap_samples: 100
