samples:
    - name: .*-16S
      reference: silva-16S
    - name: .*-ITS
      reference: unite

report_dir: report/public/01-classification
threads: 10

reads:
    preprocess:
        trimmed:
            method: trimmomatic
            temporary: False
            crop: 500
            quality: 20
            headcrop: 20
            minlen: 35

    report:
        quality_report:
            method: fastqc
            read_types:
                - original
                - trimmed

classification:
    read_based:
        method: metaxa2
        confidence: 0.8

    report:
        taxonomic_counts:
            pieplot:
                method: krona

            count_table:
                method: custom
                tax_levels:
                    - class
                    - genus

            barplot:
                method: custom
                formats:
                    - png
                    - svg
                tax_levels:
                    - class
                    - genus