sequencing: paired_end
samples:                            # List of sample categories to be analysed
    - name: example.*               # Regex expression of sample names to be analysed (reads/original/example.*_R1.fastq.gz)
      reference: mhv                 # Reference genome for reads in the category (reference/mhv/mhv.fa)

report_dir: report/public/01-corona-consensus  # Generated reports and essential output files would be stored there
threads: 16                         # Number of threads to use in analysis

reads:                              # Prepare reads and quality reports for downstream analysis
    preprocess:                     # Pre-process of reads, eliminate sequencing artifacts, contamination ...
        trimmed:                    # Remove low quality parts of reads
            method: trimmomatic     # Supported values: trimmomatic
            temporary: True        # If True, generated files would be removed after successful analysis
            crop: 275               # Maximal number of bases in read to keep. Longer reads would be truncated.
            quality: 20             # Minimal average quality of read bases to keep (inside sliding window of length 5)
            headcrop: 0            # Number of bases to remove from the start of read
            minlen: 20              # Minimal length of trimmed read. Shorter reads would be removed.

        decontaminated:             # Eliminate fragments from known artificial source, e.g. contamination by human
            method: bowtie2         # Supported values: bowtie2
            references:             # List of reference genomes
                - grch38_decoy
            keep: False              # Keep reads mapped to references (True) or remove them as contamination (False)

    report:                         # Summary reports of read characteristics to assess their quality
        quality_report:             # HTML summary report of read quality
            method: fastqc          # Supported values: fastqc
            read_types:             # List of preprocess steps for quality reports
                - original
                - trimmed
                - decontaminated

mapping:                            # Find the most similar genomic region to reads in reference (mapping process)
    mapper:                         # Method for mapping
        method: bwa                 # Supported values: bowtie2, bwa
        temporary: True

    index:                          # Generate .bai index for mapped reads in .bam files
        method: samtools            # Supported values: samtools

    postprocess:                    # Successive steps to refine mapped reads
        sorted:
            method: samtools
            temporary: True
        deduplicated:               # Mark duplicated reads (PCR duplicated)
            method: picard          # Supported values: picard

    report:                         # Summary reports of mapping process and results
        quality_report:             # HTML summary with quality of mappings
            method: qualimap        # Supported values: qualimap
            map_types:              # List of post-process steps for quality reports
                - deduplicated

variant:                                    # Identify variation in reads given reference genome
    caller:                                 # Method for variant identification
#        method: freebayes
#        min_mapping_quality: 50       # Exclude alignments from analysis if they have a mapping quality less than Q.  default: 1
#        min_base_quality: 20          # Exclude alleles from analysis if their supporting base quality is less than Q.  default: 0
#        min_alternate_count: 3        # Require at least this fraction of observations supporting an alternate allele within a single individual in the in order to evaluate the position.
#        min_alternate_fraction: 0.5   # Require at least this count of observations supporting an alternate allele within a single individual in the in order to evaluate the position.
#        min_coverage: 3               # Require at least this coverage to process a site. default: 0
#        all_alleles: False            # Report all alleles, not only those which are in called genotypes.
#        gvcf: False                   # Write gVCF output, which indicates coverage in uncalled regions, emitting a record for all bases.
#        ploidy: 1                     # Sets the default ploidy for the analysis to N.  default: 2

        method: bcftools
        min_base_quality: 0           # Minimum base quality for a base to be considered. [0]
        min_mapping_quality: 13       # Minimum mapping quality for an alignment to be used. [13]
        keep_alts: True            # Report all alleles, not only those which are in called genotypes. [False]
        ploidy: 1                     # Set predefined ploidy. [GRCh38]
        redo_baq: True                # Recalculate base alignment quality on the fly [False]
        adjust_mq: 50                 # Coefficient for downgrading mapping quality [0]
        gap_frac: 0.05                # Minimum fraction of gapped reads [0.002]

    postprocess:
        normalized:
            method: bcftools
            multiallelic: False

        filtered:
            method: bcftools
            snp_gap: 3
            indel_gap: 10
            set_gts: '.'
            include: 'INFO/DP>=3 & QUAL>=5 & GQ>=20 & GT="alt"'
            trim_alt_alleles: True

    report:
        calling:
            method: gatk

        summary:
            method: custom

consensus:                              # consensus sequence
    fasta:                              # create consesnus sequence based on vcf of a sample and reference fasta
        method: bcftools                # Allowed: 'bcftools', 'ivar' (consensus per ref regions), 'ivar_nonregional'
        mask_lte_coverage: 4            # Valid for 'bcftools'. Mask bases with N where coverage is lower than or equal to parameter.
        count_orphans: False            # Valid for ivar. True or False (def: False), whether to count anomalous read pairs in variant calling
        no_base_alignment_quality: True # Valid for ivar. True or False (def: False), on True disable base alignment quality.
        max_depth: 8000                 # Valid for ivar. Int (def: 8000), limits the number of reads to load in memory per input file. Setting to 0 removes the limit.
        min_mapping_quality: 0          # Valid for ivar. Int (def: 0), minimum mapping quality for an alignment to be used.
        min_base_quality: 13            # Valid for ivar. Int (def: 13), minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
        ivar_quality_threshold: 20      # Valid for ivar. Int, (def: 20), minimum quality score threshold to count base.
        ivar_frequency_threshold: 0     # Valid for ivar. Float, range [0-1] (default: 0), minimum frequency threshold to call consensus.
        ivar_min_depth: 10              # Valid for ivar. Int (def: 10), minimum depth to call consensus.

    summary:
        method: cat                 # concatenate consensus sequences from the samples into a single file

lineage:
    caller:
        method: pangolin
    summary:
        method: cat

