samples:                             # List of sample categories to be analysed
    - name: example.*                # Regex expression of sample names to be analysed (reads/original/example.*_R1.fastq.gz)
      reference: mhv                 # Reference genome for reads in the category (reference/mhv/mhv.fa)

report_dir: report/public/01-deepvariant # Generated reports and essential output files would be stored there
threads: 16                          # Number of threads to use in analysis

reads:                              # Prepare reads and quality reports for downstream analysis
    report:                         # Summary reports of read characteristics to assess their quality
        quality_report:             # HTML summary report of read quality
            method: fastqc          # Supported values: fastqc
            read_types:             # List of preprocess steps for quality reports
                - original

mapping:                            # Find the most similar genomic region to reads in reference (mapping process)
    mapper:                         # Method for mapping
        method: bwa                 # Supported values: bowtie2, bwa
        temporary: True

    index:                          # Generate .bai index for mapped reads in .bam files
        method: sambamba            # Supported values: samtools, sambamba

    postprocess:                    # Successive steps to refine mapped reads
        sorted:                     # Order reads according to their genomic position
            method: samtools        # Supported values: samtools, sambamba (current version gives segmentation fault!!!)
            temporary: True         # If True, generated files would be removed after successful analysis

        deduplicated:               # Mark duplicated reads (PCR duplicated)
            method: sambamba        # Supported values: picard, sambamba
            temporary: False        # If True, generated files would be removed after successful analysis

    report:                         # Summary reports of mapping process and results
        quality_report:             # HTML summary with quality of mappings
            method: qualimap        # Supported values: qualimap
            map_types:              # List of post-process steps for quality reports
                - sorted
                - deduplicated


variant:                            # Identify variation in reads given reference genome
    caller:                         # Method for variant identification
        method: deepvariant         # Supported values: vardict, gatk, deepvariant

#    postprocess:
#        annotated:
#            method: vep             # Variant Effect Predictor
#            assembly: GRCh38
#            plugins:
#                dbnsfp:
#                    - ALL           # list of dbNSFP columns, use "ALL" for every column

    report:
        calling:
            method: gatk

        summary:
            method: custom