sample_pattern: .*
reference:
    mhv: example

panel:
    mhv: wgs

report_dir: report/public/01-mapping
threads: 16

reads:
    preprocess:
        trimmed:
            method: trimmomatic
            temporary: False
            crop: 500
            quality: 20
            headcrop: 20
            minlen: 35

        decontaminated:
            method: bowtie2
            temporary: False
            references:
                - mhv
            keep: True

        deduplicated:
            method: fastuniq
            temporary: False

    report:
        quality_report:
            method: fastqc
            read_types:
                - trimmed
                - deduplicated

mapping:
    mapper:
        method: bowtie2
        params: --very-sensitive
        only_concordant: False

    index:
        method: samtools

    postprocess:
        original:
            temporary: True
        sorted:
            method: samtools
            temporary: False
        deduplicated:
            method: picard

    report:
        quality_report:
            method: qualimap
            map_types:
                - deduplicated