# Load configuration file
configfile: srcdir('config.yaml')

# Run startup scripts that automatically loads imports from src/ and load helper methods
include: config['snakelines_dir'] + '/src/snakelines.snake'

# Import sub-workflows
include: config['snakelines_dir'] + '/pipeline/standard_analysis/mapping/Snakefile.rule'

rule all:
    """
    """
    input:
        rules.finalise__map_reads_to_reference.output