# Import sub-workflows
include: config['snakelines_dir'] + '/pipeline/standard_analysis/read_quality_report/Snakefile.rule'
include: config['snakelines_dir'] + '/pipeline/standard_analysis/preprocess/Snakefile.rule'
include: config['snakelines_dir'] + '/pipeline/standard_analysis/mapping/Snakefile.rule'

# Load configuration file
configfile: srcdir('config.yaml')

# Run startup scripts that automatically loads imports from src/ and load helper methods
include: config['snakelines_dir'] + '/src/snakelines.snake'

# Find in configuration map post-process types for which should be report generated
map_types_with_quality_report = extract_from_config(config, ['mapping', 'report', 'quality_report', 'map_types'], [])

# References with at least 2 samples
multisample_references = [reference for reference in pipeline.references if len(pipeline.samples_for(reference)) > 1]
