report_dir: public/01-multiple_alignment

sequences: 'reference/clones/clones.fa'    # Fasta file with sequences to align

iqtree:                          # Generate phylogenetic tree from contig clusters
    model: GTR+I+G4              # Model to use for phylo tree generation - see iqtree documentation for more detail
