trim:
    read_type: original
    quality: 20
    headcrop: 15
    minlen: 35

mapping:
    read_type: trimmed
    reference: hg38
    params: --very-sensitive
    read_group:
        map_type: ''
    dedup:
        map_type: read_group
    realign:
        map_type: dedup

variant:
    panel: truseq
    map_type: realign
    hard_filter:
        min_nonref_allele_freq: 0.05
        min_alternate_count: 2
        min_map_quality: 15
    soft_filter:
        min_map_quality: 20
        read_depth: 10
        min_nonref_allele_freq: 0.05
        min_mean_base_quality: 20
    dbsnp_version: v150


