sample_pattern: .*                # Regex expression which samples from reads/original should be analysed

report_dir: public/01-matam       # Summaries would be copied at report/<report_dir> at the end of pipeline execution
                                  # if you choose public/<subdir>, reports would be accessible from web through
                                  # https://gen-clc.cusp.uniba.sk/<project>/<subdir>

gene_pattern:                    # Split samples into different groups based on reference gene database
    silva-ssu-128: .*16S.*       # Here, for example all samples with 16S in name would be analysed against
    refseq: .*ITS.*              #        gene sequences stored in reference/silva-ssu-128/silva-ssu-128.fa

trim:                                   # Pre-process of reads, eliminate low quality sequences
    read_type: original                 # Location of fastq files, would be searched in reads/<read_type>/*_R1.fastq.gz
    crop: 500                           # Cut the read to a specified length
    quality: 20                         # Cut read, once the average quality within the 5bp window falls below a threshold
    headcrop: 20                         # Cut the specified number of bases from the start of the read
    minlen: 35                          # Drop the read if it is below a specified length
    temporary: True                     # Trimmed fastq files are deleted after all rules that use it as an input are completed

join:                            # Join paired reads to simulate single-end sequencing (Matam requires it)
    read_type: trimmed           # What type of reads should be used for join (reads/<read_type>)

matam:                           # Assembler for metagenomic reads
    cluster_limit: 97            # Cluster genes from the reference gene sequences - This is threshold for sequence similarity
    min_scaffold_length: 300     # Shorter assembled scaffold would be filtered

otu:                             # Cluster assembled contigs according to the sequence similarity
    cluster_limit: 97            # Similarity threshold to assign sequences into the same cluster

iqtree:                          # Generate phylogenetic tree from contig clusters
    model: GTR+I+G4              # Model to use for phylo tree generation - see iqtree documentation for more detail


blast:
    enabled: True                 # Do you want to generate blast reports?

    reference:
        refseq:
            query_type: nucleotide        # Nucleotide or protein, according to sequence type in input .fa files
            target_type: nucleotide       # Nucleotide or protein, according to sequence type in blast database
            max_target_seqs: 1            # Number of best hit reference sequences from blast database for each input sequence

        silva-ssu-128:
            query_type: nucleotide        # Nucleotide or protein, according to sequence type in input .fa files
            target_type: nucleotide       # Nucleotide or protein, according to sequence type in blast database
            max_target_seqs: 1            # Number of best hit reference sequences from blast database for each input sequence
