samples:                             # List of sample categories to be analysed
    - reference: lacto_supplied            # Reference genome for reads in the category (reference/mhv/mhv.fa)

report_dir: report/public/01-phylogeny

reference:
    alignment:
        method: mafft

    phylogeny:
        method: iqtree
        model: GTR+I+G4              # Model to use for phylo tree generation - see iqtree documentation

    report:
        phylogenetic_tree:
            method: phylo

        comparison:
            method: msaviewer