samples:                                   # List of sample categories to be analysed
    - reference: lacto_supplied            # Reference genome for reads in the category (reference/lacto_supplied/lacto_supplied.fa)

report_dir: report/public/01-phylogeny     # Generated reports and essential output files would be stored there

reference:                                 # Prepare and analyse reference sequences
    alignment:                             # Multiple alignment of reference sequences
        method: mafft                      # Supported values: mafft

    phylogeny:                             # Assess phylogenetic relationship between sequences
        method: iqtree                     # Supported values: iqtree
        model: GTR+I+G4                    # Model to use for phylo tree generation - see iqtree documentation

    report:                                # Visually assess relationship between reference sequences
        phylogenetic_tree:                 # Visual inspection of distances between sequences in tree graph structure
            method: phylo                  # Supported values: phylo

        comparison:                        # Interactive HTML visualization of multiple alignment
            method: msaviewer              # Supported values: msaviewer